server {
  listen 80;
  server_name nozomu-ac.top www.nozomu-ac.top;

  location / {
    return 301 https://$host$request_uri;
  }

  location /.well-known/acme-challenge {
    root /acme;
  }
}

server {
  listen 443 ssl;
  server_name nozomu-ac.top www.nozomu-ac.top;
  ssl_certificate /etc/letsencrypt/live/my_site/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/my_site/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';

  location /subscribe/fqwp8u289jfaj2938 {
    alias /subscribe/config.yml;
  }
}
